baseURL = 'https://anamcd-lab.github.io/portfolio/'
languageCode = 'en-us'
title = "Ana's portfolio"
theme = "basic"
[params]
author = "Anita Corpus"
description = "My portfolio site"
gh_url = "https://api.github.com/users"
gh_user = "AnaMCD-lab"
